name: Deploy to Cloud Run Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCS_PROJECT_ID }}"
          workload_identity_provider: "${{ vars.GCS_WIP }}"
          service_account: "${{ vars.GCS_SERVICE_ACCOUNT_EMAIL }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCS_PROJECT_ID }}

      - name: Cloud Run Jobs Deploy
        run: |
          gcloud run jobs deploy your-job-name \
            --source ./cloudrun \
            --tasks 1 \
            --max-retries 5 \
            --region asia-northeast1 \
            --project ${{ vars.GCS_PROJECT_ID }}
